const StoreModulesNames = [
  'ProjectsStore',
  'FaqsStore',
  'PagesStore',
  'DivisionsStore',
  'CommentsStore',
  'EmployeesStore',
  'UsersStore',
  'NewsStore',
  'AcademicsStore',
  'HeadsStore',
  'TeachersStore',
  'VisitsApplicationsStore',
  'SupportMessagesStore',
  'VisitingRulesStore',
  'VacanciesStore',
  'VacancyResponsesStore',
  'MapNodesStore',
  'SpecializationsStore',
  'DietsStore',
  'DietsGroupsStore',
  'MapRoutesStore',
  'QuestionsStore',
  'TimetablesStore',
  'TimetablesPatternsStore',
];

export default StoreModulesNames;
